version: '3.2'

services:

  postgresql_local:
    build: docker/postgres/.
    env_file:
      - env/local.pg.env
    ports:
      - '5454:5432'
    networks:
      - iposter_network_local
    volumes:
      - pg_data_local:/var/lib/postgresql/data

  minio_local:
    image: minio/minio
    command: server /export --console-address ":9001"
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - iposter_network_local
    volumes:
      - minio_data_local:/export

volumes:
  pg_data_local:
  minio_data_local:

networks:
  iposter_network_local:
    driver: bridge
