name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended
          # for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install libraries
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yaml up -d
          npm run test:cov
